#!/usr/bin/env bash
# Resolve config.yaml `gpu_stack:` (gke-managed|operator|none) into the DCGM metrics scrape target —
# platform/dcgm-metrics/{kustomization.yaml,podmonitor.generated.yaml} (the dcgm-metrics Argo app
# kustomize-builds this dir). Mirrors resolve-secret-store: a committed generated artifact rendered from
# a config knob, so the GPU-stack swap is GitOps-native instead of a hand-edited PodMonitor that Argo
# self-heal would re-assert. See ADR-0001 (GKE-managed vs Operator).
#
#   gke-managed (default) = scrape GKE's managed dcgm-exporter (gke-managed-system) via a PodMonitor.
#   operator              = the NVIDIA GPU Operator ships its OWN dcgm-exporter ServiceMonitor (chart
#                           default; Prometheus discovers it cluster-wide), so dcgm-metrics renders
#                           nothing. The gpu-operator group deploys the operator (resolve-groups).
#   none                  = no GPU metrics (CPU-only): empty kustomization, no scrape object.
# No new deps (awk only).
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

ENV="${ENV:-ai-dev}"
CFG="${CFG:-environments/${ENV}/config.yaml}"
DIR="${DIR:-platform/dcgm-metrics}"
[ -f "$CFG" ] || { echo "resolve-gpu: missing $CFG" >&2; exit 1; }

field() { awk -v k="$1" '$0 ~ "(^| )"k":" { sub(".*"k":[ \t]*",""); sub(/[ \t,}#].*/,""); gsub(/["]/,""); print; exit }' "$CFG"; }

GPU_STACK="$(field gpu_stack)"; GPU_STACK="${GPU_STACK:-gke-managed}"
case "$GPU_STACK" in gke-managed|operator|none) ;; *) echo "resolve-gpu: unknown gpu_stack '$GPU_STACK' — use gke-managed|operator|none" >&2; exit 1;; esac

MON="$DIR/podmonitor.generated.yaml"
KUST="$DIR/kustomization.yaml"
hdr="# GENERATED by scripts/resolve-gpu.sh from $CFG (gpu_stack: $GPU_STACK) — do not edit; run make resolve-groups.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization"

if [ "$GPU_STACK" != gke-managed ]; then
  # operator: the GPU Operator chart's bundled dcgm-exporter ServiceMonitor handles scraping.
  # none: no GPU metrics. Either way dcgm-metrics renders an empty (valid) kustomization.
  rm -f "$MON"
  printf '%s\nresources: []\n' "$hdr" >"$KUST"
  echo "resolve-gpu ($ENV): gpu_stack=$GPU_STACK → no PodMonitor (empty $KUST)"
  exit 0
fi

printf '%s\nresources:\n  - podmonitor.generated.yaml\n' "$hdr" >"$KUST"
cat >"$MON" <<'EOF'
# GENERATED by scripts/resolve-gpu.sh (gpu_stack: gke-managed) — do not edit; run make resolve-groups.
# Scrape GKE's managed dcgm-exporter (gke-managed-system). On GKE the GPU stack is managed (ADR-0001)
# and GKE runs a per-GPU-node dcgm-exporter with an embedded DCGM engine + pod→GPU attribution; running
# our own would conflict. Prometheus discovers PodMonitors cluster-wide (podMonitorSelectorNilUsesHelmValues: false).
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gke-dcgm-exporter
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: ["gke-managed-system"]
  selector:
    matchLabels:
      app.kubernetes.io/name: gke-managed-dcgm-exporter
  podMetricsEndpoints:
    - port: metrics
      interval: 15s
      path: /metrics
EOF
echo "resolve-gpu ($ENV): gpu_stack=gke-managed → PodMonitor (gke-managed-system)"
