#!/usr/bin/env bash
# Resolve config.yaml `secret_store_auth:` (workload-identity|sa-key) into the ESO ClusterSecretStore
# auth block — platform/external-secrets/config/clustersecretstore.yaml (the artifact the
# external-secrets-config Argo app kustomize-builds). Mirrors resolve-groups / resolve-profile: a
# committed *.generated artifact rendered from a config knob, so the off-GKE swap is GitOps-native
# instead of a manual kubectl override that Argo self-heal would re-assert (the Hetzner proof).
#
# WHY a knob, not two files: the base store is hardcoded to GKE Workload Identity; an off-GKE SA-key
# store has the SAME metadata.name, so Argo would fight a hand-applied variant. Selecting the auth from
# config makes the rendered store the single source of truth ESO + Argo agree on.
#
#   workload-identity (default) = keyless GKE WI (ESO controller KSA → GSA; no stored credential)
#   sa-key                      = static SA JSON key in Secret `secret-store-key` (off-GKE / any cloud)
#
# The backend stays gcpsm + the same projectID either way (auth choice ≠ backend swap; see README).
#
# secret_backend (default gcpsm): gcpsm renders the full store from config (auth knob above). Any
# other value renders a PLACEHOLDER store with a stubbed provider block — the operator fills it per the
# ESO provider docs and this script then leaves a hand-configured non-gcpsm store alone on each run.
# No new deps (awk only).
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

ENV="${ENV:-ai-dev}"
CFG="${CFG:-environments/${ENV}/config.yaml}"
OUT="${OUT:-platform/external-secrets/config/clustersecretstore.yaml}"
[ -f "$CFG" ] || { echo "resolve-secret-store: missing $CFG" >&2; exit 1; }

field() { awk -v k="$1" '$0 ~ "(^| )"k":" { sub(".*"k":[ \t]*",""); sub(/[ \t,}#].*/,""); gsub(/["]/,""); print; exit }' "$CFG"; }

BACKEND="$(field secret_backend)"; BACKEND="${BACKEND:-gcpsm}"

if [ "$BACKEND" != gcpsm ]; then
  # Non-gcpsm: render a PLACEHOLDER store once, then leave it for the operator to fill. The store name
  # stays `secret-store` so every ExternalSecret is unchanged; only the provider block changes.
  # NON-CLOBBER: once the operator fills the provider (no placeholder sentinel, no gcpsm block left),
  # leave the file untouched so a later resolve-groups run never wipes a hand-edited backend.
  if [ -f "$OUT" ] && ! grep -q 'replace with your provider' "$OUT" && ! grep -q 'gcpsm:' "$OUT"; then
    echo "resolve-secret-store ($ENV): secret_backend=$BACKEND → leaving hand-configured $OUT untouched." >&2
    exit 0
  fi
  cat >"$OUT" <<EOF
# GENERATED by scripts/resolve-secret-store.sh from $CFG (secret_backend: $BACKEND) — PLACEHOLDER.
# Fill the provider block below per the ESO provider docs, then this store is yours to manage.
# The cluster-wide binding to your secret backend. Every ExternalSecret references it by name
# (secret-store), so only this provider block changes when you swap backends.
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secret-store
spec:
  provider:
    # FILL THIS IN for secret_backend: $BACKEND — see https://external-secrets.io/latest/provider/
    # Examples (pick one, delete the rest):
    #   awssm:        { service: SecretsManager, region: <region>, auth: { ... } }   # AWS Secrets Manager
    #   azurekv:      { vaultUrl: https://<vault>.vault.azure.net, authType: ... }    # Azure Key Vault
    #   vault:        { server: https://<vault>:8200, path: secret, version: v2, auth: { ... } }  # HashiCorp Vault / OpenBao
    #   kubernetes:   { remoteNamespace: <ns>, server: { ... }, auth: { ... } }       # in-cluster Secrets
    {}  # <- replace with your provider; resolve-secret-store will not overwrite a non-gcpsm store's intent
EOF
  echo "resolve-secret-store ($ENV): secret_backend=$BACKEND → wrote PLACEHOLDER $OUT" >&2
  echo "resolve-secret-store: fill spec.provider per https://external-secrets.io/latest/provider/ (gcpsm is the only auto-rendered backend)." >&2
  exit 0
fi

AUTH="$(field secret_store_auth)"; AUTH="${AUTH:-workload-identity}"
case "$AUTH" in workload-identity|sa-key) ;; *) echo "resolve-secret-store: unknown secret_store_auth '$AUTH' — use workload-identity|sa-key" >&2; exit 1;; esac
PROJECT="$(field projectID)"
[ -n "$PROJECT" ] || { echo "resolve-secret-store: cluster.projectID missing in $CFG" >&2; exit 1; }

cat >"$OUT" <<EOF
# GENERATED by scripts/resolve-secret-store.sh from $CFG (secret_store_auth: $AUTH) — do not edit;
# run make resolve-secret-store (or resolve-groups, which chains it). The cluster-wide binding to the
# secret backend (gcpsm). Every ExternalSecret references this store by name (secret-store).
# Fork note: swap the provider here to retarget a different backend (AWS SM / Azure KV / Vault /
# OpenBao / the \`fake\` provider for local). Every ExternalSecret stays identical.
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secret-store
spec:
  provider:
    gcpsm:
      projectID: $PROJECT
EOF

if [ "$AUTH" = sa-key ]; then
  cat >>"$OUT" <<'EOF'
      # Off-GKE: authenticate with a static SA JSON key (Secret secret-store-key) instead of
      # Workload Identity. Seed it once (see platform/external-secrets/README.md "off-GKE setup").
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: secret-store-key
            key: sa-key.json
            namespace: external-secrets
EOF
fi

echo "resolve-secret-store ($ENV): secret_store_auth=$AUTH → wrote $OUT"
