#!/usr/bin/env bash
# Resolve config.yaml `profile:` (cost|dev|prod) into committed HA overlays — the economic tier knob
# (ADR-0029 SR3). cost|dev keep the cheap single-replica lab default; prod turns on minimal HA. Runtime
# manifests stay verbatim (ADR-0031): this only writes generated *.generated overlays Helm/kustomize
# layer ON TOP of the static base. No new deps (awk only).
#
# Writes:
#   clusters/<env>/litellm-profile.generated.yaml  — Helm values overlay (applied last → overrides base)
#   platform/litellm/db/kustomization.yaml          — CNPG build root (instances + snapshot backups)
#   platform/litellm/db/scheduledbackup.generated.yaml — prod only (removed for cost|dev)
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

ENV="${ENV:-ai-dev}"
CFG="${CFG:-environments/${ENV}/config.yaml}"
VALUES_OUT="${VALUES_OUT:-clusters/${ENV}/litellm-profile.generated.yaml}"
DB_DIR="${DB_DIR:-platform/litellm/db}"
[ -f "$CFG" ] || { echo "resolve-profile: missing $CFG" >&2; exit 1; }

field() { awk -v k="$1" '$0 ~ "(^| )"k":" { sub(".*"k":[ \t]*",""); sub(/[ \t,}#].*/,""); gsub(/["]/,""); print; exit }' "$CFG"; }

PROFILE="$(field profile)"; PROFILE="${PROFILE:-cost}"
case "$PROFILE" in cost|dev|prod) ;; *) echo "resolve-profile: unknown profile '$PROFILE' — use cost|dev|prod" >&2; exit 1;; esac

if [ "$PROFILE" = prod ]; then
  replicas=2; redis=true; db_unavailable=false; pdb=true; instances=3
else
  replicas=1; redis=false; db_unavailable=true; pdb=false; instances=1
fi

# CNPG storageClass is no longer injected: cluster.yaml omits it and inherits the cluster default,
# like every other PVC.

cat >"$VALUES_OUT" <<EOF
# GENERATED by scripts/resolve-profile.sh from $CFG (profile: $PROFILE) — do not edit.
# Last-applied Helm values overlay for the litellm release; overrides platform/litellm/values.yaml.
replicaCount: $replicas
redis:
  enabled: $redis
EOF
if [ "$PROFILE" = prod ]; then
  cat >>"$VALUES_OUT" <<'EOF'
  architecture: standalone   # budget/rate cache only; HA-Redis (Sentinel/cluster) deferred
  # Bitnami relocated its free images to the bitnamilegacy repo; the chart default docker.io/bitnami/redis
  # is being retired, so pin the legacy image by digest to keep the prod redis subchart pullable.
  image:
    registry: docker.io
    repository: bitnamilegacy/redis
    digest: sha256:c1843bcdb2f413d2aff67adbaf482082673cd40ec602fa9fefad74ec685cb813
    tag: 7.2.4-debian-12-r9
pdb:
  enabled: true
  minAvailable: 1
EOF
fi
cat >>"$VALUES_OUT" <<EOF
# Nest under proxy_config to deep-merge over the base proxy_config.general_settings; a top-level
# general_settings key is ignored by the chart, leaving prod silently fail-open.
proxy_config:
  general_settings:
    allow_requests_on_db_unavailable: $db_unavailable   # false = fail-closed budgets, prod only (ADR-0029 SR3)
EOF

SB_OUT="$DB_DIR/scheduledbackup.generated.yaml"
warns=""
if [ "$PROFILE" = prod ]; then
  cat >"$SB_OUT" <<EOF
# GENERATED by scripts/resolve-profile.sh (profile: prod) — do not edit.
# Daily VolumeSnapshot of litellm-pg PGDATA. No WAL archive (no barman/GCS) → cold backup only
# (no PITR); see cluster.yaml backup.volumeSnapshot.online: false.
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: litellm-pg-snapshot
spec:
  cluster:
    name: litellm-pg
  method: volumeSnapshot
  schedule: "0 0 2 * * *"
  backupOwnerReference: cluster
EOF
  cat >"$DB_DIR/kustomization.yaml" <<EOF
# GENERATED by scripts/resolve-profile.sh from $CFG (profile: prod) — do not edit; run make resolve-profile.
# LiteLLM prerequisites: the CNPG Postgres Cluster + ESO secrets. Applied before the LiteLLM Helm
# release (separate Argo app, later sync-wave). prod patches the Cluster to HA (instances:3, CNPG
# auto-creates its own PDB) + cold VolumeSnapshot backups, and adds the ScheduledBackup.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litellm
resources:
  - cluster.yaml
  - externalsecret-pg.yaml
  - externalsecret-litellm.yaml
  - externalsecret-grafana-ro.yaml
  - scheduledbackup.generated.yaml
patches:
  - target:
      kind: Cluster
      name: litellm-pg
    patch: |
      - op: replace
        path: /spec/instances
        value: 3
      - op: add
        path: /spec/backup
        value:
          volumeSnapshot:
            online: false
EOF
  warns="  ! prod: VolumeSnapshot backups need the CSI external-snapshotter (VolumeSnapshot CRDs) and a\n  ! default VolumeSnapshotClass in the cluster. CNPG omits className → inherits the default.\n"
else
  rm -f "$SB_OUT"
  cat >"$DB_DIR/kustomization.yaml" <<EOF
# GENERATED by scripts/resolve-profile.sh from $CFG (profile: $PROFILE) — do not edit; run make resolve-profile.
# LiteLLM prerequisites: the CNPG Postgres Cluster + ESO secrets. Applied before the LiteLLM Helm
# release (separate Argo app, later sync-wave). cost|dev = single-instance base, no backups.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litellm
resources:
  - cluster.yaml
  - externalsecret-pg.yaml
  - externalsecret-litellm.yaml
  - externalsecret-grafana-ro.yaml
EOF
fi

echo "resolve-profile ($ENV): profile=$PROFILE → wrote $VALUES_OUT, $DB_DIR/kustomization.yaml (instances=$instances)"
[ -z "$warns" ] || printf "%b" "$warns"
