#!/usr/bin/env bash
# Resolve config.yaml `features.guardrails` into the LiteLLM guardrails values overlay
# clusters/<env>/litellm-guardrails.generated.yaml (ADR-0034, approach a). The guardrails proxy_config
# block is injected into the LiteLLM release ONLY when the feature is on, so the base values never
# reference the Presidio services while the `guardrails` group is absent. When off, an empty no-op
# overlay is written so the LiteLLM Application's valueFiles list always resolves. Chained from
# `make resolve-groups`. No new deps (awk only).
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

ENV="${ENV:-ai-dev}"
CFG="${CFG:-environments/${ENV}/config.yaml}"
OUT="${OUT:-clusters/${ENV}/litellm-guardrails.generated.yaml}"
NS="${GUARDRAILS_NS:-guardrails}"
[ -f "$CFG" ] || { echo "resolve-guardrails: missing $CFG" >&2; exit 1; }

feat() { # feature-name -> "true"/"false" (default false)
  local v; v="$(awk -v k="$1" '$0 ~ "^  "k":" { sub("^  "k":[ \t]*",""); gsub(/[ \t"#].*$/,""); print; exit }' "$CFG")"
  case "$v" in true) echo true;; *) echo false;; esac
}

if [ "$(feat guardrails)" != true ]; then
  cat >"$OUT" <<EOF
# GENERATED by scripts/resolve-guardrails.sh from $CFG (features.guardrails: false) — do not edit.
# Guardrails OFF → no LiteLLM guardrails registered (the Presidio group is not deployed). The base
# platform/litellm/values.yaml stays clean. Enable with \`features.guardrails: true\` then \`make resolve-groups\`.
{}
EOF
  echo "resolve-guardrails ($ENV): guardrails=false → wrote no-op $OUT"
  exit 0
fi

cat >"$OUT" <<EOF
# GENERATED by scripts/resolve-guardrails.sh from $CFG (features.guardrails: true) — do not edit.
# Layered onto platform/litellm/values.yaml (ADR-0034): two always-on tenant-edge guardrails.
#   A) presidio-pii-mask     — Presidio masks PII in the prompt BEFORE it leaves LiteLLM (request continues).
#   B) prompt-injection-block — litellm_content_filter BLOCKs jailbreak/override prompts (HTTP 400).
# Presidio analyzer+anonymizer come from the \`guardrails\` catalog group (namespace ${NS}).
proxy_config:
  guardrails:
    - guardrail_name: presidio-pii-mask
      litellm_params:
        guardrail: presidio
        mode: pre_call
        default_on: true
        presidio_analyzer_api_base: http://presidio-analyzer.${NS}.svc.cluster.local:3000/
        presidio_anonymizer_api_base: http://presidio-anonymizer.${NS}.svc.cluster.local:3000/
        pii_entities_config:
          EMAIL_ADDRESS: MASK
          PHONE_NUMBER: MASK
          CREDIT_CARD: MASK
          US_SSN: MASK
          IBAN_CODE: MASK
    - guardrail_name: prompt-injection-block
      litellm_params:
        guardrail: litellm_content_filter
        mode: pre_call
        default_on: true
        categories:
          - { category: prompt_injection_jailbreak, enabled: true, action: BLOCK, severity_threshold: medium }
          - { category: prompt_injection_system_prompt, enabled: true, action: BLOCK, severity_threshold: medium }
          - { category: prompt_injection_data_exfiltration, enabled: true, action: BLOCK, severity_threshold: medium }
EOF
echo "resolve-guardrails ($ENV): guardrails=true → wrote $OUT"
