name: lint-docs

on:
  pull_request:
    paths:
      - docs/public/**
      - .vale.ini
      - styles/**
      - .github/workflows/lint-docs.yml
  push:
    branches: [main]
    paths:
      - docs/public/**
      - .vale.ini
      - styles/**

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: errata-ai/vale-action@d89dee975228ae261d22c15adcd03578634d429c # v2
        with:
          files: docs/public
          fail_on_error: true
