name: lint-docs

on:
  pull_request:
    paths:
      - docs/public/**
      - .vale.ini
      - styles/**
      - .github/workflows/lint-docs.yml
  push:
    branches: [main]
    paths:
      - docs/public/**
      - .vale.ini
      - styles/**

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - uses: errata-ai/vale-action@518a9136acc6e6668ce7c00d367051e0941e87ff # v3.0.0
        with:
          files: docs/public
          fail_on_error: true
