name: lint-docs

on:
  pull_request:
    paths:
      - docs/public/**
      - .vale.ini
      - styles/**
      - .github/workflows/lint-docs.yml
  push:
    branches: [main]
    paths:
      - docs/public/**
      - .vale.ini
      - styles/**

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: errata-ai/vale-action@d89dee975228ae261d22c15adcd03578634d429c # v2
        with:
          files: docs/public
          fail_on_error: true
